"
" Pheo's ~/.vimrc
"

" Line Numbers
set number

" Highlight Syntax
syntax on

" Show non-\x20 chars (\t, &nbsp)
set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

" Two-\x20 Indents & Tabs
set shiftwidth=2
set tabstop=2
"set expandtab "uncomment for \t to \x20

" Start Folds uncollapsed
set foldmethod=syntax
set nofoldenable

" Disable automatic comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Cross-platform clipboard
set clipboard^=unnamed,unnamedplus
"set paste

" Color Scheme
colorscheme slate
